"use client";

import Avatar from "boring-avatars";
import { AnimatePresence, motion } from "framer-motion";
import { Flame, FlaskConical, Lock, LogOut, Scan, Search, SlidersHorizontal, X } from "lucide-react";
import { Fragment, useCallback, useEffect, useRef, useState } from "react";
import { Drawer } from "vaul";

import { HapticButton } from "@/components/haptic-button";
import { QrScanner } from "@/components/qr-scanner";
import { TokenAmount } from "@/components/token-amount";
import { ConnectWalletControl } from "@/components/wallet-connect";
import { useTranslations } from "@/i18n/locale-provider";
import {
	pinPriorityChains,
	relayChains,
	relayTokens,
} from "@/lib/relay/token-list";
import { useHeldTokens } from "@/lib/use-held-tokens";
import { useVolumeRanking } from "@/lib/use-volume-ranking";
import { cn } from "@/lib/utils";

/**
 * Stateful token selector used for both the "From" and "To" sides. Before a
 * token is picked it shows a "From..." / "To..." placeholder; picking a token
 * swaps in a stacked icon (Boring Avatar + chain + asset) with the address /
 * chain / name plus side-specific meta (Test/Max + holdings for From,
 * Slippage/Fee for To). The "To" drawer adds an enter/paste address field with
 * a QR scanner. Static data — asset/chain icons come from Relay's icon CDN and
 * the address avatar is generated with boring-avatars.
 */

type Variant = "from" | "to";

export interface TokenRow {
	name: string;
	symbol: string;
	chain: string;
	chainId: number;
	address: string;
	logo: string;
	amount: string;
	usd: string;
	/** Token decimals — required to convert display amounts to on-chain base units. */
	decimals: number;
	/** Chain VM family, for routing execution (EVM today; SVM guarded). */
	vmType?: "evm" | "svm";
}

/** USD price per unit of a token: total usd ÷ holdings. 0 if NaN / divide-by-zero. */
export function price(token: TokenRow) {
	const usd = Number.parseFloat(token.usd.replace(/[^0-9.]/g, "")) || 0;
	const amount = Number.parseFloat(token.amount) || 0;
	if (!(usd > 0) || !(amount > 0)) return 0;
	return usd / amount;
}

const ADDRESS = "0x71•••976F";
const AVATAR_COLORS = ["#7dd3fc", "#3b82f6", "#2563eb", "#1e3a8a", "#0ea5e9"];

/** Shorten a wallet address (EVM or Solana) to `1234…wxyz` for display. */
function truncateAddress(addr: string) {
	return addr.length <= 12 ? addr : `${addr.slice(0, 6)}…${addr.slice(-4)}`;
}

const LOGO = {
	sol: "https://coin-images.coingecko.com/coins/images/4128/large/solana.png",
	usdc: "https://coin-images.coingecko.com/coins/images/6319/large/usdc.png",
	wbtc: "https://coin-images.coingecko.com/coins/images/7598/large/wrapped_bitcoin_wbtc.png",
	eth: "https://assets.relay.link/icons/1/light.png",
	usdt: "https://coin-images.coingecko.com/coins/images/325/large/Tether.png",
	cbeth: "https://coin-images.coingecko.com/coins/images/27008/large/cbeth.png",
};

const chainIcon = (chainId: number) =>
	`https://assets.relay.link/icons/${chainId}/light.png`;

// The full whitelist of Relay-supported tokens (Uniswap token-list format),
// generated by `bun run build:tokens`. Holdings are unknown here (amount/usd are
// 0) until real wallet balances are wired in.
const TOKENS: TokenRow[] = relayTokens;

/** How many top-volume assets to surface in the "Hot" section (distinct symbols). */
const HOT_COUNT = 6;


function tokenKey(t: TokenRow) {
	// chainId + address is the canonical, unique identity (name+chain collides for
	// a handful of cross-listed tokens, which breaks React keys + selection).
	return `${t.chainId}-${t.address}`;
}

/** Fuzzy match: case-insensitive substring or in-order subsequence. */
function fuzzyMatch(query: string, text: string) {
	const q = query.toLowerCase().replace(/\s+/g, "");
	const t = text.toLowerCase();
	if (t.includes(q)) return true;
	let qi = 0;
	for (let ti = 0; ti < t.length && qi < q.length; ti++) {
		if (t[ti] === q[qi]) qi++;
	}
	return qi === q.length;
}

/** Format a slippage fraction as a percent string with trailing zeros trimmed. */
function formatPct(fraction: number) {
	return `${Number((fraction * 100).toFixed(4))}%`;
}

/** Test amount: 1% of holdings, capped at ~$1 worth of the asset. */
function computeTest(token: TokenRow) {
	const usd = Number.parseFloat(token.usd.replace(/[^0-9.]/g, "")) || 0;
	const amount = Number.parseFloat(token.amount) || 0;
	if (usd <= 0 || amount <= 0) return "0";
	const test = Math.min(0.01 * amount, amount / usd);
	return String(Number(test.toFixed(8)));
}

function ChainBadge({ chainId, className }: { chainId: number; className?: string }) {
	return (
		// eslint-disable-next-line @next/next/no-img-element
		<img
			src={chainIcon(chainId)}
			alt=""
			className={cn("size-4 rounded-full bg-card object-cover ring-2 ring-card", className)}
		/>
	);
}

function TokenIcon({ token }: { token: TokenRow }) {
	return (
		<div className="relative size-11 shrink-0">
			{/* eslint-disable-next-line @next/next/no-img-element */}
			<img
				src={token.logo}
				alt={token.name}
				className="size-11 rounded-full bg-background object-cover"
			/>
			<ChainBadge chainId={token.chainId} className="absolute bottom-0 right-0" />
		</div>
	);
}

function AssetStack({ token, seed = ADDRESS }: { token: TokenRow; seed?: string }) {
	return (
		<div className="relative h-14 w-7 shrink-0">
			<div className="absolute left-1/2 top-0 size-7 -translate-x-1/2 overflow-hidden rounded-full ring-2 ring-card">
				<Avatar size={28} name={seed} variant="marble" colors={AVATAR_COLORS} />
			</div>
			{/* eslint-disable-next-line @next/next/no-img-element */}
			<img
				src={chainIcon(token.chainId)}
				alt={token.chain}
				className="absolute left-1/2 top-3.5 size-7 -translate-x-1/2 rounded-full bg-card object-cover ring-2 ring-card"
			/>
			{/* eslint-disable-next-line @next/next/no-img-element */}
			<img
				src={token.logo}
				alt={token.name}
				className="absolute left-1/2 top-7 size-7 -translate-x-1/2 rounded-full bg-card object-cover ring-2 ring-card"
			/>
		</div>
	);
}

function ClickablePill({
	onClick,
	children,
}: {
	onClick: (e: React.MouseEvent) => void;
	children: React.ReactNode;
}) {
	return (
		<HapticButton
			type="button"
			onClick={onClick}
			wrapperClassName="pointer-events-auto inline-grid"
			className="inline-flex cursor-pointer items-center gap-1.5 rounded-full bg-foreground/[0.07] px-3 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-foreground/[0.12]"
		>
			{children}
		</HapticButton>
	);
}

function SelectedMeta({
	variant,
	token,
	onSetAmount,
	slippage,
	fee,
	feeLoading,
	onOpenSlippage,
}: {
	variant: Variant;
	token: TokenRow;
	onSetAmount?: (amount: string) => void;
	slippage?: number;
	fee?: number | null;
	feeLoading?: boolean;
	onOpenSlippage?: () => void;
}) {
	const t = useTranslations();
	const feeAmount = feeLoading ? "…" : fee != null ? `$${fee.toFixed(2)}` : "—";
	if (variant === "to") {
		return (
			<div className="flex flex-col items-end gap-2">
				<ClickablePill
					onClick={(e) => {
						e.stopPropagation();
						onOpenSlippage?.();
					}}
				>
					<SlidersHorizontal className="size-3.5" />
					{t("tokenDrawer.meta.slippage", { percent: formatPct(slippage ?? 0.005) })}
				</ClickablePill>
				<span className="text-sm text-muted-foreground">
					{t("tokenDrawer.meta.fee", { amount: feeAmount })}
				</span>
			</div>
		);
	}
	const set = (amount: string) => (e: React.MouseEvent) => {
		e.stopPropagation();
		onSetAmount?.(amount);
	};
	// No holdings known for this token (catalog without wallet balances) — show
	// nothing on the right rather than Test/Max/"0".
	if (Number.parseFloat(token.amount) <= 0) return null;
	return (
		<div className="flex flex-col items-end gap-2">
			<div className="flex gap-2">
				<ClickablePill onClick={set(computeTest(token))}>
					<FlaskConical className="size-3.5" />
					{t("tokenDrawer.action.test")}
				</ClickablePill>
				<ClickablePill onClick={set(token.amount)}>{t("tokenDrawer.action.max")}</ClickablePill>
			</div>
			<span className="text-sm text-muted-foreground">
				<TokenAmount value={token.amount} /> {token.symbol}
			</span>
		</div>
	);
}

function SelectedHeader({
	variant,
	token,
	walletAddress,
	onSetAmount,
	slippage,
	fee,
	feeLoading,
	onOpenSlippage,
}: {
	variant: Variant;
	token: TokenRow;
	walletAddress?: string | null;
	onSetAmount?: (amount: string) => void;
	slippage?: number;
	fee?: number | null;
	feeLoading?: boolean;
	onOpenSlippage?: () => void;
}) {
	return (
		<div className="flex items-start justify-between gap-3">
			<div className="flex items-center gap-3">
				<AssetStack token={token} seed={walletAddress ?? ADDRESS} />
				<div className="flex flex-col leading-none -space-y-0.5">
					<span className="text-sm text-muted-foreground">
						{walletAddress ? truncateAddress(walletAddress) : ADDRESS}
					</span>
					<span className="text-sm text-muted-foreground">{token.chain}</span>
					<span className="text-base font-semibold text-foreground">{token.name}</span>
				</div>
			</div>
			<SelectedMeta
				variant={variant}
				token={token}
				onSetAmount={onSetAmount}
				slippage={slippage}
				fee={fee}
				feeLoading={feeLoading}
				onOpenSlippage={onOpenSlippage}
			/>
		</div>
	);
}

export function TokenBox({
	variant,
	selected = null,
	triggerClassName,
	onSelect,
	onSetAmount,
	slippage,
	fee,
	feeLoading,
	onOpenSlippage,
	connected,
	walletAddress,
	onConnect,
	onDisconnect,
	genAddress,
	onToggleGenAddress,
	open: openProp,
	onOpenChange,
}: {
	variant: Variant;
	/** Controlled selected token (owned by the parent so the flip can swap them). */
	selected?: TokenRow | null;
	triggerClassName?: string;
	onSelect?: (token: TokenRow) => void;
	onSetAmount?: (amount: string) => void;
	slippage?: number;
	/** Live total fee in USD from the quote (null until it resolves / for sends). */
	fee?: number | null;
	/** Whether a fresh quote is loading (so the fee can show a placeholder). */
	feeLoading?: boolean;
	onOpenSlippage?: () => void;
	connected?: boolean;
	/** Connected wallet address (EVM or Solana), or null when disconnected. */
	walletAddress?: string | null;
	onConnect?: () => void;
	onDisconnect?: () => void;
	genAddress?: boolean;
	onToggleGenAddress?: () => void;
	/**
	 * Controlled open state. Omit to let the drawer own it. SwapFrom/SwapTo pass
	 * it so the amount area below the trigger can open the same picker.
	 */
	open?: boolean;
	onOpenChange?: (open: boolean) => void;
}) {
	const t = useTranslations();
	// Real-time volume-proxy ranking. From = "withdraw" (source side), To =
	// "deposit" (destination side). Direction is wired now but applied
	// identically until a real directional bridge-flow feed exists.
	const { data: volumeData, sortTokens, sortChains } = useVolumeRanking();
	const direction = variant === "from" ? "withdraw" : "deposit";
	// Optionally controlled. `setOpen` is identity-stable and reads its inputs
	// through refs, so the Cmd+F/Cmd+K effect below (which intentionally does not
	// re-subscribe on every render) can't capture a stale closure.
	const [uncontrolledOpen, setUncontrolledOpen] = useState(false);
	const isControlled = openProp !== undefined;
	const open = isControlled ? openProp : uncontrolledOpen;
	const controlledRef = useRef(isControlled);
	controlledRef.current = isControlled;
	const onOpenChangeRef = useRef(onOpenChange);
	onOpenChangeRef.current = onOpenChange;
	const setOpen = useCallback((next: boolean) => {
		if (!controlledRef.current) setUncontrolledOpen(next);
		onOpenChangeRef.current?.(next);
	}, []);
	const [query, setQuery] = useState("");
	const [activeChainId, setActiveChainId] = useState<number | null>(null);
	// "From" lists only the assets the connected wallet holds (multicall
	// balances); "To" lists the full catalog.
	const { tokens: heldTokens, loading: heldLoading } = useHeldTokens(
		variant === "from",
	);
	const sourceTokens =
		variant === "from" && connected ? (heldTokens ?? []) : TOKENS;
	const searchRef = useRef<HTMLInputElement>(null);
	const listRef = useRef<HTMLDivElement>(null);
	const [activeIndex, setActiveIndex] = useState(0);
	// "To" address field + QR scanner state.
	const [address, setAddress] = useState("");
	const [scanning, setScanning] = useState(false);
	const label =
		variant === "from" ? t("tokenDrawer.variant.from") : t("tokenDrawer.variant.to");

	// Keyboard shortcut (web): ⌘F / Ctrl+F opens the From search, ⌘K / Ctrl+K
	// opens the To search.
	useEffect(() => {
		const onKey = (e: KeyboardEvent) => {
			if (!(e.metaKey || e.ctrlKey) || e.altKey || e.shiftKey) return;
			const k = e.key.toLowerCase();
			if ((variant === "from" && k === "f") || (variant === "to" && k === "k")) {
				e.preventDefault();
				setOpen(true);
			}
		};
		window.addEventListener("keydown", onKey);
		return () => window.removeEventListener("keydown", onKey);
	}, [variant]);

	// Focus the search field when opened on web (skip mobile to avoid popping up
	// the on-screen keyboard).
	useEffect(() => {
		if (!open || !window.matchMedia("(min-width: 768px)").matches) return;
		const t = setTimeout(() => searchRef.current?.focus(), 150);
		return () => clearTimeout(t);
	}, [open]);

	const q = query.trim();
	const filtered = sourceTokens.filter((tok) => {
		if (activeChainId !== null && tok.chainId !== activeChainId) return false;
		if (q === "") return true;
		return fuzzyMatch(q, `${tok.name} ${tok.symbol} ${tok.chain} ${tok.address}`);
	});

	// Sort AFTER filtering, on a copy (sortTokens never mutates), so the live
	// volume proxy reorders the visible list without corrupting the shared
	// catalog. Recomputes whenever the proxy data updates (real-time).
	const ranked = sortTokens(filtered, direction);

	// Pull the highest-volume assets into a separate "Hot" section at the top —
	// only on the full, unfiltered list (no search, no chain filter) and only
	// once real volume data has loaded, so the split is meaningful. We take the
	// top distinct symbols (one row per symbol, on its highest-volume chain) from
	// the already volume-ranked list, then drop them from the remainder so nothing
	// is listed twice.
	const canSection =
		q === "" &&
		activeChainId === null &&
		Object.keys(volumeData.bySymbol).length > 0;
	let hot: TokenRow[] = [];
	let rest = ranked;
	if (canSection) {
		const seenSym = new Set<string>();
		const picked: TokenRow[] = [];
		for (const tok of ranked) {
			const sym = tok.symbol.toUpperCase();
			if (seenSym.has(sym)) continue;
			seenSym.add(sym);
			picked.push(tok);
			if (picked.length >= HOT_COUNT) break;
		}
		// Worth splitting only with a few hot rows and a non-empty remainder.
		if (picked.length >= 3 && ranked.length > picked.length) {
			const hotKeys = new Set(picked.map(tokenKey));
			hot = picked;
			rest = ranked.filter((tok) => !hotKeys.has(tokenKey(tok)));
		}
	}
	// Single flat list for keyboard nav + rendering: hot rows first, then the
	// rest. Section headers are injected at the boundaries during render. When not
	// sectioning, this is just the ranked list.
	const displayList = hot.length > 0 ? [...hot, ...rest] : ranked;

	// Chain filter chips: ranked by aggregate proxy volume, then the pinned
	// chains lifted back to the front (copy, no mutation of the shared
	// relayChains const). Pin last so volume ranking can't bury a pinned chain
	// once /api/volume resolves.
	const sortedChains = pinPriorityChains(sortChains(relayChains, direction));

	const filteredRef = useRef(displayList);
	filteredRef.current = displayList;
	const activeRef = useRef(activeIndex);
	activeRef.current = activeIndex;

	const selectToken = (t: TokenRow) => {
		setOpen(false);
		setQuery("");
		onSelect?.(t);
	};

	// Reset the keyboard highlight when the list opens or the query changes.
	useEffect(() => {
		setActiveIndex(0);
	}, [open, query]);

	// While open: ↑/↓ move the highlight, Enter selects the highlighted token.
	useEffect(() => {
		if (!open) return;
		const onKey = (e: KeyboardEvent) => {
			const list = filteredRef.current;
			if (e.key === "ArrowDown") {
				e.preventDefault();
				setActiveIndex((i) => Math.min(i + 1, list.length - 1));
			} else if (e.key === "ArrowUp") {
				e.preventDefault();
				setActiveIndex((i) => Math.max(i - 1, 0));
			} else if (e.key === "Enter") {
				const t = list[activeRef.current];
				if (t) {
					e.preventDefault();
					selectToken(t);
				}
			}
		};
		window.addEventListener("keydown", onKey);
		return () => window.removeEventListener("keydown", onKey);
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [open]);

	// Keep the highlighted row scrolled into view.
	useEffect(() => {
		if (!open) return;
		listRef.current
			?.querySelector('[data-active="true"]')
			?.scrollIntoView({ block: "nearest" });
	}, [activeIndex, open]);

	return (
		<Drawer.Root
			open={open}
			onOpenChange={(next) => {
				setOpen(next);
				// Drop the camera + scanner view whenever the sheet closes.
				if (!next) setScanning(false);
			}}
		>
			<div
				className={cn(
					"relative block text-left transition-colors",
					triggerClassName,
				)}
			>
				{/* Full-area tap target that opens the drawer (with haptics). It sits
				    behind a pass-through content layer; the pills re-enable pointer
				    events so they act on their own without opening the drawer. */}
				<div className="absolute inset-0">
					<HapticButton
						type="button"
						onClick={() => setOpen(true)}
						aria-label={t("tokenDrawer.trigger.selectTokenAriaLabel", { label })}
						wrapperClassName="grid size-full"
						className="size-full cursor-pointer"
					/>
				</div>
				<div className="pointer-events-none relative flex min-h-[3.75rem] flex-col justify-center">
					<AnimatePresence mode="wait" initial={false}>
						{selected ? (
							<motion.div
								key="selected"
								initial={{ opacity: 0 }}
								animate={{ opacity: 1 }}
								exit={{ opacity: 0 }}
								transition={{ duration: 0.2, ease: "easeOut" }}
							>
								<SelectedHeader
									variant={variant}
									token={selected}
									walletAddress={walletAddress}
									onSetAmount={onSetAmount}
									slippage={slippage}
									fee={fee}
									feeLoading={feeLoading}
									onOpenSlippage={onOpenSlippage}
								/>
							</motion.div>
						) : (
							<motion.div
								key="placeholder"
								initial={{ opacity: 0 }}
								animate={{ opacity: 1 }}
								exit={{ opacity: 0 }}
								transition={{ duration: 0.2, ease: "easeOut" }}
							>
								<span className="token-box-label block text-5xl font-semibold text-foreground/30">
									{t("tokenDrawer.placeholder.label", { label })}
								</span>
								<kbd className="pointer-events-none absolute right-0 top-1/2 hidden h-5 -translate-y-1/2 select-none items-center gap-1 rounded border bg-muted px-1.5 font-mono text-[10px] font-medium text-muted-foreground md:inline-flex">
									<span className="text-xs">⌘</span>
									{variant === "from" ? "F" : "K"}
								</kbd>
							</motion.div>
						)}
					</AnimatePresence>
				</div>
			</div>

			<Drawer.Portal>
				<Drawer.Overlay className="fixed inset-0 z-50 bg-black/60" />
				<Drawer.Content
					aria-describedby={undefined}
					className="fixed inset-x-0 bottom-0 z-50 mx-auto flex h-[88vh] max-w-md flex-col rounded-t-3xl bg-card outline-none"
				>
					<div className="mx-auto mt-3 h-1.5 w-12 shrink-0 rounded-full bg-foreground/20" />

					<div className="flex flex-col gap-4 px-3 pt-4">
						<div className="flex items-center justify-between">
							<Drawer.Title className="text-2xl font-bold text-foreground">
								{label}
							</Drawer.Title>
							<Drawer.Close className="flex size-9 cursor-pointer items-center justify-center rounded-full bg-foreground/10 text-muted-foreground transition-colors hover:bg-foreground/15">
								<X className="size-5" />
							</Drawer.Close>
						</div>

						{variant === "from" ? (
							connected ? (
								<div className="flex items-stretch gap-3">
									<div className="flex flex-1 items-center gap-3 rounded-2xl bg-foreground/[0.06] px-4 py-3.5">
										<div className="size-7 shrink-0 overflow-hidden rounded-full">
											<Avatar
												size={28}
												name={walletAddress ?? ADDRESS}
												variant="marble"
												colors={AVATAR_COLORS}
											/>
										</div>
										<span className="flex-1 text-lg font-semibold text-foreground">
											{walletAddress ? truncateAddress(walletAddress) : "0x71C7...976F"}
										</span>
										<Lock className="size-4 shrink-0 text-muted-foreground" />
									</div>
									<button
										type="button"
										onClick={() => onDisconnect?.()}
										aria-label="Log out"
										className="flex shrink-0 items-center justify-center rounded-2xl bg-foreground/[0.06] px-5 text-muted-foreground transition-colors hover:bg-foreground/10 hover:text-foreground active:scale-95"
									>
										<LogOut className="size-5" />
									</button>
								</div>
							) : (
								<ConnectWalletControl
									onConnect={() => onConnect?.()}
									genAddress={genAddress ?? false}
									onToggleGenAddress={() => onToggleGenAddress?.()}
								/>
							)
						) : (
							<AnimatePresence mode="wait" initial={false}>
								{scanning ? (
									<motion.div
										key="scanner"
										initial={{ opacity: 0, height: 0 }}
										animate={{ opacity: 1, height: "auto" }}
										exit={{ opacity: 0, height: 0 }}
										transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
										className="flex flex-col gap-3 overflow-hidden"
									>
										<QrScanner
											onScan={(addr) => {
												setAddress(addr);
												setScanning(false);
											}}
										/>
										<HapticButton
											type="button"
											onClick={() => setScanning(false)}
											wrapperClassName="block w-full"
											className="h-12 w-full rounded-2xl bg-foreground/[0.06] text-base font-semibold text-foreground transition-colors hover:bg-foreground/10"
										>
											{t("tokenDrawer.action.cancel")}
										</HapticButton>
									</motion.div>
								) : (
									<motion.div
										key="input"
										initial={{ opacity: 0 }}
										animate={{ opacity: 1 }}
										exit={{ opacity: 0 }}
										transition={{ duration: 0.18, ease: "easeOut" }}
										className="flex gap-2"
									>
										<input
											type="text"
											value={address}
											onChange={(e) => setAddress(e.target.value)}
											placeholder={
												walletAddress
													? truncateAddress(walletAddress)
													: t("tokenDrawer.input.addressPlaceholder")
											}
											autoComplete="off"
											autoCorrect="off"
											spellCheck={false}
											className="h-[3.25rem] min-w-0 flex-1 rounded-2xl bg-foreground/[0.06] px-4 text-base text-foreground placeholder:text-muted-foreground focus:outline-none"
										/>
										<HapticButton
											type="button"
											onClick={() => setScanning(true)}
											aria-label={t("tokenDrawer.action.scanQrAriaLabel")}
											wrapperClassName="grid size-[3.25rem] shrink-0"
											className="flex size-full items-center justify-center rounded-2xl bg-foreground/[0.06] text-muted-foreground transition-colors hover:bg-foreground/10"
										>
											<Scan className="size-5" />
										</HapticButton>
									</motion.div>
								)}
							</AnimatePresence>
						)}

						<div className="flex items-center gap-3 rounded-2xl bg-foreground/[0.06] px-4 py-3">
							<Search className="size-5 shrink-0 text-muted-foreground" />
							<input
								ref={searchRef}
								type="text"
								value={query}
								onChange={(e) => setQuery(e.target.value)}
								placeholder={t("tokenDrawer.input.searchPlaceholder")}
								className="flex-1 bg-transparent text-base text-foreground placeholder:text-muted-foreground focus:outline-none"
							/>
						</div>

						<div className="-mx-3 flex gap-2 overflow-x-auto px-3 pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
							<button
								type="button"
								onClick={() => {
									setActiveChainId(null);
									setActiveIndex(0);
								}}
								className={cn(
									"flex shrink-0 cursor-pointer items-center gap-2 rounded-full py-2 pl-2 pr-4 text-sm font-semibold transition-colors",
									activeChainId === null
										? "bg-foreground text-background"
										: "bg-foreground/[0.06] text-foreground hover:bg-foreground/10",
								)}
							>
								<span className="size-6 rounded-full border-2 border-current" />
								{t("tokenDrawer.filter.all")}
							</button>
							{sortedChains.map((c) => (
								<button
									key={c.chainId}
									type="button"
									onClick={() => {
										setActiveChainId(c.chainId);
										setActiveIndex(0);
									}}
									className={cn(
										"flex shrink-0 cursor-pointer items-center gap-2 rounded-full py-2 pl-2 pr-4 text-sm font-semibold transition-colors",
										activeChainId === c.chainId
											? "bg-foreground text-background"
											: "bg-foreground/[0.06] text-foreground hover:bg-foreground/10",
									)}
								>
									{/* eslint-disable-next-line @next/next/no-img-element */}
									<img
										src={c.icon}
										alt=""
										className="size-6 rounded-full bg-background object-cover"
									/>
									{c.name}
								</button>
							))}
						</div>
					</div>

					<div
						ref={listRef}
						className="scroll-fade scrollbar-subtle mt-2 min-h-0 flex-1 overflow-y-auto px-3 pb-8"
					>
						{displayList.length === 0 && (
							<p className="py-8 text-center text-sm text-muted-foreground">
								{variant === "from" && connected && heldLoading
									? "Loading your tokens…"
									: t("tokenDrawer.empty.noTokensFound")}
							</p>
						)}
						{displayList.map((token, i) => {
							const isSelected = selected !== null && tokenKey(selected) === tokenKey(token);
							return (
								<Fragment key={tokenKey(token)}>
									{/* Section headers, injected at the hot/rest boundaries. */}
									{hot.length > 0 && i === 0 && (
										<div className="flex items-center gap-1.5 px-2 pb-1.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
											<Flame className="size-3.5" />
											{t("tokenDrawer.section.hot")}
										</div>
									)}
									{hot.length > 0 && i === hot.length && (
										<div className="px-2 pb-1.5 pt-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
											{t("tokenDrawer.section.all")}
										</div>
									)}
									<HapticButton
										type="button"
										data-active={i === activeIndex}
										wrapperClassName="mb-2 block w-full"
										onClick={() => selectToken(token)}
										className={cn(
											"flex w-full cursor-pointer items-center gap-3 rounded-full py-2 pl-2 pr-4 text-left transition-colors",
											i === activeIndex
												? "bg-foreground/10"
												: "hover:bg-foreground/10",
											isSelected && "opacity-50",
										)}
									>
										<TokenIcon token={token} />
										<div className="min-w-0 flex-1">
											<p className="font-semibold text-foreground">{token.name}</p>
											<p className="text-sm text-muted-foreground">
												{token.chain}
												{isSelected ? t("tokenDrawer.row.selectedSuffix") : ""}
											</p>
										</div>
										{Number.parseFloat(token.amount) > 0 && (
											<div className="text-right">
												<p className="font-semibold text-foreground">
													<TokenAmount value={token.amount} />
												</p>
												<p className="text-sm text-muted-foreground">
													{token.usd}
												</p>
											</div>
										)}
									</HapticButton>
								</Fragment>
							);
						})}
					</div>
				</Drawer.Content>
			</Drawer.Portal>
		</Drawer.Root>
	);
}
